name: CI devops 2023
on:
  #to begin, you want to launch this job in the main and develop
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      #checkout your GitHub code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      #do the same with another action (actions/setup-java@v3) that enables to set up jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17


      #finally, build your app with the latest command
      - name: Build and test with Maven
        working-directory: "backend-api"
        run: mvn clean verify

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend-api
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend-api:latest

      - name: Build and push database
        uses: docker/build-push-action@v2
        with:
          context: ./database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

      - name: Build and push http-server
        uses: docker/build-push-action@v2
        with:
          context: ./http-server
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-http-server:latest

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend-api
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/master' }}
